import 'transfer_template_page_specs.dart';
import 'transfer_template_page_style_set.dart';

class QTransferTemplatePage extends TransferTemplatePageSpecs {
  final TransferTemplatePageStyleSet style;
  const QTransferTemplatePage({
    super.key,
    required super.behaviour,
    required super.inputBehaviour,
    required this.style,
    required super.appBarTitle,
    required super.titlePage,
    required super.subtitlePage,
    required super.moneyInputDescription,
    required super.primaryButtonText,
    required super.secondaryButtonText,
    required super.initialValue,
    required super.primaryButtonBehaviour,
    required super.coinType,
    required super.accountBalance,
    required super.showBalance,
    super.onBackButtonPressed,
    super.inputHintSemantics,
    super.onInputIconTap,
    super.onValueChange,
    super.primaryButtonHintSemantics,
    super.secondaryButtonHintSemantics,
    super.primaryButtonSemantics,
    super.secondaryButtonSemantics,
    super.onPrimaryButtonPressed,
    super.onSecondaryButtonPressed,
    super.secondaryButtonBehaviour,
    super.hintAccountBalanceLabel,
  }) : super(styles: style);

  /// Construtor com estilo padrão para as telas de transferência
  const QTransferTemplatePage.standard({
    super.key,
    required super.behaviour,
    required super.inputBehaviour,
    required super.appBarTitle,
    required super.titlePage,
    required super.subtitlePage,
    required super.moneyInputDescription,
    required super.primaryButtonText,
    required super.secondaryButtonText,
    required super.initialValue,
    required super.primaryButtonBehaviour,
    required super.accountBalance,
    super.onBackButtonPressed,
    super.showBalance = false,
    super.coinType,
    super.inputHintSemantics,
    super.onInputIconTap,
    super.onValueChange,
    super.primaryButtonHintSemantics,
    super.secondaryButtonHintSemantics,
    super.primaryButtonSemantics,
    super.secondaryButtonSemantics,
    super.onPrimaryButtonPressed,
    super.onSecondaryButtonPressed,
    super.secondaryButtonBehaviour,
    super.hintAccountBalanceLabel,
  })  : style = TransferTemplatePageStyleSet.standard,
        super(
          styles: TransferTemplatePageStyleSet.standard,
        );
  const QTransferTemplatePage.standardWithoutBalance({
    super.key,
    required super.behaviour,
    required super.inputBehaviour,
    required super.appBarTitle,
    required super.titlePage,
    required super.primaryButtonText,
    required super.secondaryButtonText,
    required super.initialValue,
    required super.primaryButtonBehaviour,
    super.onBackButtonPressed,
    super.coinType,
    super.inputHintSemantics,
    super.onInputIconTap,
    super.onValueChange,
    super.primaryButtonHintSemantics,
    super.secondaryButtonHintSemantics,
    super.primaryButtonSemantics,
    super.secondaryButtonSemantics,
    super.onPrimaryButtonPressed,
    super.onSecondaryButtonPressed,
    super.secondaryButtonBehaviour,
  })  : style = TransferTemplatePageStyleSet.standard,
        super(
          styles: TransferTemplatePageStyleSet.standard,
          showBalance: null,
          accountBalance: null,
          subtitlePage: null,
          moneyInputDescription: null,
        );
  const QTransferTemplatePage.scheduling({
    super.key,
    required super.behaviour,
    required super.inputBehaviour,
    required super.appBarTitle,
    required super.titlePage,
    required super.subtitlePage,
    required super.moneyInputDescription,
    required super.primaryButtonText,
    required super.secondaryButtonText,
    required super.initialValue,
    required super.primaryButtonBehaviour,
    required super.accountBalance,
    required super.scheduleDateLabel,
    required super.scheduleDateValue,
    required super.scheduleFrequencyLabel,
    required super.scheduleFrequencyValue,
    required super.onScheduleDatePressed,
    required super.onScheduleFrequencyPressed,
    super.onBackButtonPressed,
    super.showBalance = false,
    super.coinType,
    super.inputHintSemantics,
    super.onInputIconTap,
    super.onValueChange,
    super.primaryButtonHintSemantics,
    super.secondaryButtonHintSemantics,
    super.primaryButtonSemantics,
    super.secondaryButtonSemantics,
    super.onPrimaryButtonPressed,
    super.onSecondaryButtonPressed,
    super.secondaryButtonBehaviour,
  })  : style = TransferTemplatePageStyleSet.standard,
        super(
          styles: TransferTemplatePageStyleSet.standard,
        );
}
