part of 'icon_specs.dart';

enum IconStyleSet {
  size16SecondaryBase,
  size20SecondaryBase,
  size20White,
  size14White,
  size12Gray3,
  size24Success,
  size16Success0,
  size16Black,
  size24Warning,
  size16Gray5,
  size24Gray5,
  size24Gray7,
  size24Gray3,
  size12Gray1,
  size24Error,
  size28Gray5,
  size24SecondaryBase,
  size24Red,
  size24White,
  size24PrimaryBase,
  size24PrimaryBaseDark,
  size28Ciano,
  size32Gray5,
  size32Error,
  size32Black,
  size32Gray1,
  size36White,
  size72SuccessBase,
  size72ErrorBase,
  size72WarningBase,
  size130Gray5,
  size28Gray7,
  size48ErrorBase,
  size28Secondary,
  size72WarningLight,
  size72Gray5;

  const IconStyleSet();

  IconStyles get specs {
    return switch (this) {
      size16SecondaryBase => IconSpecs.size16SecondaryBaseStyle,
      size20SecondaryBase => IconSpecs.size20SecondaryBaseStyle,
      size20White => IconSpecs.size20WhiteStyle,
      size14White => IconSpecs.size14WhiteStyle,
      size12Gray3 => IconSpecs.size12Gray3Style,
      size16Success0 => IconSpecs.size16Success0Style,
      size16Black => IconSpecs.size16BlackStyle,
      size24Success => IconSpecs.size24SuccessStyle,
      size24Warning => IconSpecs.size24WarningStyle,
      size16Gray5 => IconSpecs.size16Gray5Style,
      size24Gray5 => IconSpecs.size24Gray5Style,
      size24Gray7 => IconSpecs.size24Gray7Style,
      size24Gray3 => IconSpecs.size24Gray3Style,
      size12Gray1 => IconSpecs.size12Gray1Style,
      size24Error => IconSpecs.size24Error,
      size28Gray5 => IconSpecs.size28Gray5Style,
      size24SecondaryBase => IconSpecs.size24SecondaryBaseStyle,
      size24Red => IconSpecs.size24RedStyle,
      size24White => IconSpecs.size24WhiteStyle,
      size24PrimaryBase => IconSpecs.size24PrimaryBaseStyle,
      size24PrimaryBaseDark => IconSpecs.size24PrimaryBaseDarkStyle,
      size28Ciano => IconSpecs.size28CianoStyle,
      size32Gray5 => IconSpecs.size32Gray5Style,
      size32Black => IconSpecs.size32BlackStyle,
      size32Gray1 => IconSpecs.size32Gray1Style,
      size32Error => IconSpecs.size32ErrorStyle,
      size36White => IconSpecs.size36WhiteStyle,
      size72SuccessBase => IconSpecs.size72SuccessBaseStyle,
      size72ErrorBase => IconSpecs.size72ErrorBaseStyle,
      size72WarningBase => IconSpecs.size72WarningBaseStyle,
      size130Gray5 => IconSpecs.size130Gray5Style,
      size28Gray7 => IconSpecs.size28Gray7Style,
      size48ErrorBase => IconSpecs.size48ErrorBaseStyle,
      size28Secondary => IconSpecs.size28SecondaryStyle,
      size72WarningLight => IconSpecs.size72WarningLightStyle,
      size72Gray5 => IconSpecs.size72Gray5Style,
    };
  }
}
