part of 'label_specs.dart';

enum LabelStyleSet {
  h1Lato42Gray5Bold,
  h1Lato42PrimaryBold,
  h1Lato42SecondaryColorBaseBold,
  h2Lato32Gray5Bold,
  h3Lato28Gray5Bold,
  h4Lato24Gray5Bold,
  h4Lato24WhiteBold,
  h4Lato24PrimaryBaseBold,
  h5Lato20Gray5Bold,
  h5Lato20WhiteBold,
  h5Lato20BlackBold,
  h5Roboto20Gray8Bold,
  paragraphRoboto16Gray5Regular,
  paragraphRoboto16Gray9Regular,
  paragraphRoboto16Gray4Regular,
  paragraphRoboto16Gray5Bold,
  paragraphRoboto16BlackBold,
  paragraphRoboto16WhiteBold,
  paragraphRoboto16Gray1Bold,
  paragraphRoboto16Gray3Bold,
  paragraphRoboto16Gray4Bold,
  bodyRoboto20Gray8Regular,
  bodyRoboto16Gray4Medium,
  bodyRoboto16Gray5Medium,
  bodyRoboto16BlackMedium,
  bodyRoboto14WhiteMedium,
  bodyRoboto16Gray5SemiBold,
  bodyRoboto16Gray6Light,
  paragraphRoboto16PrimaryBold,
  paragraphRoboto16SuccessBold,
  paragraphRoboto16ErrorBold,
  bodyRoboto16Gray4Regular,
  bodyRoboto16Gray9Regular,
  paragraphRoboto16Bold,
  paragraphRoboto16SecondaryBold,
  paragraphRoboto14Medium,
  paragraphRoboto14HightlightSecondaryBaseStyle,
  bodyRoboto14Gray5SemiBold,
  bodyRoboto14Gray3Medium,
  bodyRoboto14Gray5Regular,
  bodyRoboto14BlackRegular,
  bodyRoboto14Gray5Medium,
  bodyRoboto14Gray3SemiBold,
  bodyRoboto14Gray6Light,
  bodyRoboto14RedMedium,
  bodyRoboto16WhiteRegular,
  bodyRoboto24WhiteBold,
  captionRoboto14ErrorRegular,
  captionRoboto14Gray5Bold,
  captionRoboto14BlackBold,
  captionRoboto14Gray3Regular,
  captionRoboto14Gray4Regular,
  captionRoboto14Gray5Regular,
  captionRoboto14SuccessRegular,
  captionRoboto12Gray4Regular,
  captionRoboto12Gray4Bold,
  captionRoboto14WhiteRegular,
  captionRoboto14WhiteBold,
  captionRoboto12Gray3Regular,
  captionRoboto12Gray5Regular,
  captionRoboto12SecondaryRegular,
  captionRoboto12Gray5Bold,
  captionRoboto12BlackRegular,
  captionRoboto12BlackBold,
  captionRoboto12SuccessBold,
  captionRoboto12WarningBold,
  captionRoboto12PrimaryBold,
  captionRoboto12ErrorBold,
  bodyRoboto14ErrorRegular,
  h4Lato24Gray6Bold,
  paragraphRoboto16Gray5SemiBold,
  bodyRoboto16Gray5Bold,
  captionRoboto12ErrorBaseRegular,
  bodyRoboto14Gray5MediumBoldSecondary,
  bodyRoboto16SecondaryBold;

  const LabelStyleSet();

  LabelStyles get specs {
    return switch (this) {
      h1Lato42Gray5Bold => LabelSpecs.h1Lato42Gray5BoldStyle,
      h1Lato42PrimaryBold => LabelSpecs.h1Lato42PrimaryBoldStyle,
      h1Lato42SecondaryColorBaseBold => LabelSpecs.h1Lato42SecondaryColorBaseBoldStyle,
      h2Lato32Gray5Bold => LabelSpecs.h2Lato32Gray5BoldStyle,
      h3Lato28Gray5Bold => LabelSpecs.h3Lato28Gray5BoldStyle,
      h4Lato24Gray5Bold => LabelSpecs.h4Lato24Gray5BoldStyle,
      h4Lato24WhiteBold => LabelSpecs.h4Lato24WhiteBoldStyle,
      h4Lato24PrimaryBaseBold => LabelSpecs.h4Lato24PrimaryBaseBoldStyle,
      h4Lato24Gray6Bold => LabelSpecs.h4Lato24Gray6BoldStyle,
      h5Lato20Gray5Bold => LabelSpecs.h5Lato20Gray5BoldStyle,
      h5Lato20WhiteBold => LabelSpecs.h5Lato20WhiteBoldStyle,
      h5Lato20BlackBold => LabelSpecs.h5Lato20BlackBoldStyle,
      h5Roboto20Gray8Bold => LabelSpecs.h5Roboto20Gray8BoldStyle,
      paragraphRoboto16Gray5Regular => LabelSpecs.paragraphRoboto16Gray5RegularStyle,
      paragraphRoboto16Gray9Regular => LabelSpecs.paragraphRoboto16Gray9RegularStyle,
      paragraphRoboto16Gray4Regular => LabelSpecs.paragraphRoboto16Gray4RegularStyle,
      paragraphRoboto16Gray5Bold => LabelSpecs.paragraphRoboto16Gray5BoldStyle,
      paragraphRoboto16BlackBold => LabelSpecs.paragraphRoboto16BlackBoldStyle,
      paragraphRoboto16WhiteBold => LabelSpecs.paragraphRoboto16WhiteBoldStyle,
      paragraphRoboto16Gray1Bold => LabelSpecs.paragraphRoboto16Gray1BoldStyle,
      paragraphRoboto16Gray3Bold => LabelSpecs.paragraphRoboto16Gray3BoldStyle,
      paragraphRoboto16Gray4Bold => LabelSpecs.paragraphRoboto16Gray4BoldStyle,
      bodyRoboto20Gray8Regular => LabelSpecs.bodyRoboto20Gray8RegularStyle,
      bodyRoboto16Gray5Medium => LabelSpecs.bodyRoboto16Gray5MediumStyle,
      bodyRoboto16BlackMedium => LabelSpecs.bodyRoboto16BlackMediumStyle,
      bodyRoboto14WhiteMedium => LabelSpecs.bodyRoboto14WhiteMediumStyle,
      bodyRoboto16Gray4Medium => LabelSpecs.bodyRoboto16Gray4MediumStyle,
      bodyRoboto16Gray5SemiBold => LabelSpecs.bodyRoboto16Gray5SemiBoldStyle,
      bodyRoboto16Gray6Light => LabelSpecs.bodyRoboto16Gray6LightStyle,
      bodyRoboto16Gray9Regular => LabelSpecs.bodyRoboto16Gray9RegularStyle,
      paragraphRoboto16PrimaryBold => LabelSpecs.paragraphRoboto16PrimaryBoldStyle,
      paragraphRoboto16SuccessBold => LabelSpecs.paragraphRoboto16SuccessBoldStyle,
      paragraphRoboto16ErrorBold => LabelSpecs.paragraphRoboto16ErrorBoldStyle,
      bodyRoboto16Gray4Regular => LabelSpecs.bodyRoboto16Gray4RegularStyle,
      paragraphRoboto16Bold => LabelSpecs.paragraphRoboto16BoldStyle,
      paragraphRoboto16SecondaryBold => LabelSpecs.paragraphRoboto16SecondaryBoldStyle,
      paragraphRoboto14Medium => LabelSpecs.paragraphRoboto14MediumStyle,
      paragraphRoboto14HightlightSecondaryBaseStyle => LabelSpecs.paragraphRoboto14HightlightSecondaryBaseStyle,
      bodyRoboto14Gray5SemiBold => LabelSpecs.bodyRoboto14Gray5SemiBoldStyle,
      bodyRoboto14Gray3Medium => LabelSpecs.bodyRoboto14Gray3MediumStyle,
      bodyRoboto14Gray5Regular => LabelSpecs.bodyRoboto14Gray5RegularStyle,
      bodyRoboto14BlackRegular => LabelSpecs.bodyRoboto14BlackRegularStyle,
      bodyRoboto14Gray5Medium => LabelSpecs.bodyRoboto14Gray5MediumStyle,
      bodyRoboto14Gray3SemiBold => LabelSpecs.bodyRoboto14Gray3SemiBoldStyle,
      bodyRoboto14Gray6Light => LabelSpecs.bodyRoboto14Gray6LightStyle,
      bodyRoboto14RedMedium => LabelSpecs.bodyRoboto14RedMediumStyle,
      bodyRoboto16WhiteRegular => LabelSpecs.bodyRoboto16WhiteRegularStyle,
      bodyRoboto24WhiteBold => LabelSpecs.bodyRoboto24WhiteBoldStyle,
      captionRoboto12Gray4Regular => LabelSpecs.captionRoboto12Gray4RegularStyle,
      captionRoboto12ErrorBaseRegular => LabelSpecs.captionRoboto12ErrorBaseRegularStyle,
      captionRoboto14Gray5Bold => LabelSpecs.captionRoboto14Gray5BoldStyle,
      captionRoboto14BlackBold => LabelSpecs.captionRoboto14BlackBoldStyle,
      captionRoboto14Gray3Regular => LabelSpecs.captionRoboto14Gray3RegularStyle,
      captionRoboto14Gray4Regular => LabelSpecs.captionRoboto14Gray4RegularStyle,
      captionRoboto14Gray5Regular => LabelSpecs.captionRoboto14Gray5RegularStyle,
      captionRoboto14SuccessRegular => LabelSpecs.captionRoboto14SuccessRegularStyle,
      captionRoboto14ErrorRegular => LabelSpecs.captionRoboto14ErrorRegularStyle,
      captionRoboto12Gray4Bold => LabelSpecs.captionRoboto12Gray4BoldStyle,
      captionRoboto14WhiteRegular => LabelSpecs.captionRoboto14WhiteRegularStyle,
      captionRoboto14WhiteBold => LabelSpecs.captionRoboto14WhiteBoldStyle,
      captionRoboto12Gray3Regular => LabelSpecs.captionRoboto12Gray3RegularStyle,
      captionRoboto12Gray5Regular => LabelSpecs.captionRoboto12Gray5RegularStyle,
      captionRoboto12SecondaryRegular => LabelSpecs.captionRoboto12SecondaryRegularStyle,
      captionRoboto12Gray5Bold => LabelSpecs.captionRoboto12Gray5BoldStyle,
      captionRoboto12SuccessBold => LabelSpecs.captionRoboto12SuccessBoldStyle,
      captionRoboto12WarningBold => LabelSpecs.captionRoboto12WarningBoldStyle,
      captionRoboto12PrimaryBold => LabelSpecs.captionRoboto12PrimaryBoldStyle,
      captionRoboto12ErrorBold => LabelSpecs.captionRoboto12ErrorBoldStyle,
      captionRoboto12BlackRegular => LabelSpecs.captionRoboto12BlackRegularStyle,
      captionRoboto12BlackBold => LabelSpecs.captionRoboto12BlackBoldStyle,
      bodyRoboto14ErrorRegular => LabelSpecs.bodyRoboto14ErrorRegularStyle,
      paragraphRoboto16Gray5SemiBold => LabelSpecs.paragraphRoboto16Gray5SemiBoldStyle,
      bodyRoboto16Gray5Bold => LabelSpecs.bodyRoboto16Gray5BoldStyle,
      bodyRoboto14Gray5MediumBoldSecondary => LabelSpecs.bodyRoboto14Gray5MediumBoldSecondaryStyle,
      bodyRoboto16SecondaryBold => LabelSpecs.bodyRoboto16SecondaryBoldStyle,
    };
  }
}
